//go:build !ignore_autogenerated

/*
Copyright 2024 KCU Knowledge Portal.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChatSpace) DeepCopyInto(out *ChatSpace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChatSpace.
func (in *ChatSpace) DeepCopy() *ChatSpace {
	if in == nil {
		return nil
	}
	out := new(ChatSpace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChatSpace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChatSpaceList) DeepCopyInto(out *ChatSpaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChatSpace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChatSpaceList.
func (in *ChatSpaceList) DeepCopy() *ChatSpaceList {
	if in == nil {
		return nil
	}
	out := new(ChatSpaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChatSpaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChatSpaceSpec) DeepCopyInto(out *ChatSpaceSpec) {
	*out = *in
	out.Outline = in.Outline
	out.Qdrant = in.Qdrant
	out.Embedding = in.Embedding
	out.RAG = in.RAG
	out.ResourceQuota = in.ResourceQuota
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChatSpaceSpec.
func (in *ChatSpaceSpec) DeepCopy() *ChatSpaceSpec {
	if in == nil {
		return nil
	}
	out := new(ChatSpaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChatSpaceStatus) DeepCopyInto(out *ChatSpaceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ResourceStatus = in.ResourceStatus
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChatSpaceStatus.
func (in *ChatSpaceStatus) DeepCopy() *ChatSpaceStatus {
	if in == nil {
		return nil
	}
	out := new(ChatSpaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddingConfig) DeepCopyInto(out *EmbeddingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddingConfig.
func (in *EmbeddingConfig) DeepCopy() *EmbeddingConfig {
	if in == nil {
		return nil
	}
	out := new(EmbeddingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutlineConfig) DeepCopyInto(out *OutlineConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutlineConfig.
func (in *OutlineConfig) DeepCopy() *OutlineConfig {
	if in == nil {
		return nil
	}
	out := new(OutlineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantConfig) DeepCopyInto(out *QdrantConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantConfig.
func (in *QdrantConfig) DeepCopy() *QdrantConfig {
	if in == nil {
		return nil
	}
	out := new(QdrantConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RAGConfig) DeepCopyInto(out *RAGConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RAGConfig.
func (in *RAGConfig) DeepCopy() *RAGConfig {
	if in == nil {
		return nil
	}
	out := new(RAGConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotaConfig) DeepCopyInto(out *ResourceQuotaConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotaConfig.
func (in *ResourceQuotaConfig) DeepCopy() *ResourceQuotaConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	*out = *in
	out.Outline = in.Outline
	out.Qdrant = in.Qdrant
	out.Embedding = in.Embedding
	out.RAG = in.RAG
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatus.
func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}
