//go:build !ignore_autogenerated

/*
Copyright 2024 KCU Knowledge Portal.
*/

// Code originally generated by controller-gen; maintained by hand because
// the type set has been extended for the Agentic Operator. DO NOT regenerate
// without comparing to the current types.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// ── ChatSpace ────────────────────────────────────────────────────────

// DeepCopyInto copies the receiver into out.
func (in *ChatSpace) DeepCopyInto(out *ChatSpace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the receiver.
func (in *ChatSpace) DeepCopy() *ChatSpace {
	if in == nil {
		return nil
	}
	out := new(ChatSpace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ChatSpace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── ChatSpaceList ────────────────────────────────────────────────────

// DeepCopyInto copies the receiver into out.
func (in *ChatSpaceList) DeepCopyInto(out *ChatSpaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		items := make([]ChatSpace, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&items[i])
		}
		out.Items = items
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *ChatSpaceList) DeepCopy() *ChatSpaceList {
	if in == nil {
		return nil
	}
	out := new(ChatSpaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ChatSpaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── Spec ─────────────────────────────────────────────────────────────

// DeepCopyInto copies the receiver into out.
func (in *ChatSpaceSpec) DeepCopyInto(out *ChatSpaceSpec) {
	*out = *in
	out.ResourceQuota = in.ResourceQuota
	out.Agentic = in.Agentic
	out.Outline = in.Outline
	out.Qdrant = in.Qdrant
	out.Embedding = in.Embedding
	out.RAG = in.RAG
}

// DeepCopy returns a deep copy of the receiver.
func (in *ChatSpaceSpec) DeepCopy() *ChatSpaceSpec {
	if in == nil {
		return nil
	}
	out := new(ChatSpaceSpec)
	in.DeepCopyInto(out)
	return out
}

// ── Status ───────────────────────────────────────────────────────────

// DeepCopyInto copies the receiver into out.
func (in *ChatSpaceStatus) DeepCopyInto(out *ChatSpaceStatus) {
	*out = *in
	out.AppliedQuota = in.AppliedQuota
	if in.AgenticActions != nil {
		actions := make([]string, len(in.AgenticActions))
		copy(actions, in.AgenticActions)
		out.AgenticActions = actions
	}
	if in.Conditions != nil {
		conds := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&conds[i])
		}
		out.Conditions = conds
	}
	out.ResourceStatus = in.ResourceStatus
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy returns a deep copy of the receiver.
func (in *ChatSpaceStatus) DeepCopy() *ChatSpaceStatus {
	if in == nil {
		return nil
	}
	out := new(ChatSpaceStatus)
	in.DeepCopyInto(out)
	return out
}

// ── Component sub-types (all value types, trivial copies) ────────────

func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) { *out = *in }
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) { *out = *in }
func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *AgenticPolicy) DeepCopyInto(out *AgenticPolicy) { *out = *in }
func (in *AgenticPolicy) DeepCopy() *AgenticPolicy {
	if in == nil {
		return nil
	}
	out := new(AgenticPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceQuotaConfig) DeepCopyInto(out *ResourceQuotaConfig) { *out = *in }
func (in *ResourceQuotaConfig) DeepCopy() *ResourceQuotaConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotaConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *OutlineConfig) DeepCopyInto(out *OutlineConfig) { *out = *in }
func (in *OutlineConfig) DeepCopy() *OutlineConfig {
	if in == nil {
		return nil
	}
	out := new(OutlineConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *QdrantConfig) DeepCopyInto(out *QdrantConfig) { *out = *in }
func (in *QdrantConfig) DeepCopy() *QdrantConfig {
	if in == nil {
		return nil
	}
	out := new(QdrantConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *EmbeddingConfig) DeepCopyInto(out *EmbeddingConfig) { *out = *in }
func (in *EmbeddingConfig) DeepCopy() *EmbeddingConfig {
	if in == nil {
		return nil
	}
	out := new(EmbeddingConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *RAGConfig) DeepCopyInto(out *RAGConfig) { *out = *in }
func (in *RAGConfig) DeepCopy() *RAGConfig {
	if in == nil {
		return nil
	}
	out := new(RAGConfig)
	in.DeepCopyInto(out)
	return out
}
